import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {paymentTotals,validateUpload} from '../src/validation.js';
test('financial totals are correct for unpaid, instalment and fully paid students',()=>{
 assert.deepEqual(paymentTotals([]),{paid:0,remaining:10000});
 assert.deepEqual(paymentTotals([{amount_kes:5000}]),{paid:5000,remaining:5000});
 assert.deepEqual(paymentTotals([{amount_kes:5000},{amount_kes:5000}]),{paid:10000,remaining:0});
});
test('assignment file validation rejects empty/oversize/disallowed files and long notes',()=>{
 assert.equal(validateUpload({name:'report.docx',size:100}), '');
 for(const file of [null,{name:'r.pdf',size:0},{name:'r.pdf',size:11*1024*1024},{name:'attack.html',size:100}])assert.ok(validateUpload(file));
 assert.ok(validateUpload({name:'r.pdf',size:100},'x'.repeat(4001)));
});
test('admin approval, letters, payment writes, assignment isolation and progress persist correctly',async()=>{
 const db=new PGlite();
 const admin='10000000-0000-4000-8000-000000000001',a='10000000-0000-4000-8000-000000000002',b='10000000-0000-4000-8000-000000000003';
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public,storage to anon,authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;grant select,insert,delete on storage.objects to authenticated;
 insert into auth.users values('${admin}','admin@example.com'),('${a}','a@example.com'),('${b}','b@example.com');`);
 await db.exec(readFileSync('supabase/schema.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/20261009_admissions_and_portal_fixes.sql','utf8'));
 await db.query('insert into app_admins(user_id) values($1)',[admin]);
 const apps=(await db.query(`insert into applications(user_id,full_name,phone,payment_plan) values($1,'Student A','0742330046','full'),($2,'Student B','0742330046','instalments') returning id,user_id`,[a,b])).rows;
 const appA=apps.find(x=>x.user_id===a).id,appB=apps.find(x=>x.user_id===b).id;
 const as=async id=>db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${id}';`);
 await as(a);
 assert.equal((await db.query('select public.is_admin() as yes')).rows[0].yes,false);
 await assert.rejects(db.query('select * from admin_list_applications()'));
 await assert.rejects(db.query('select admin_set_admission($1,$2)',[appA,'approved']));
 await assert.rejects(db.query('insert into app_admins(user_id) values($1)',[a]));
 await assert.rejects(db.query(`insert into storage.objects(bucket_id,name) values('assignments',$1)`,[a+'/before.pdf']));
 await as(admin);
 let admitted=(await db.query('select * from admin_set_admission($1,$2)',[appA,'approved'])).rows[0];
 const year=(await db.query("select extract(year from now() at time zone 'Africa/Nairobi')::integer as y")).rows[0].y;
 assert.equal(admitted.admission_no,`AIWH/ESS/0001/${year}`);
 assert.equal((await db.query('select * from admin_set_admission($1,$2)',[appA,'approved'])).rows[0].admission_no,admitted.admission_no);
 assert.equal((await db.query('select * from admin_set_admission($1,$2)',[appB,'approved'])).rows[0].admission_no,`AIWH/ESS/0002/${year}`);
 assert.equal((await db.query('select * from admin_list_applications()')).rows.length,2);
 await db.query('select admin_record_payment($1,$2,$3)',[appA,5000,'PAY-A-1']);
 await assert.rejects(db.query('select admin_record_payment($1,$2,$3)',[appA,5000,'PAY-A-1']));
 await assert.rejects(db.query('select admin_record_payment($1,$2,$3)',[appA,6000,'PAY-A-2']));
 await db.query(`insert into storage.objects(bucket_id,name) values('admission-letters',$1)`,[a+'/letter.pdf']);
 await db.query('select admin_register_letter($1,$2)',[appA,a+'/letter.pdf']);
 await as(a);
 assert.equal((await db.query('select * from admission_letters')).rows.length,1);
 await assert.rejects(db.query('select admin_register_letter($1,$2)',[appA,a+'/letter.pdf']));
 await db.query(`insert into course_progress(user_id,module_id,completed) values($1,'m1',true) on conflict(user_id,module_id) do update set user_id=excluded.user_id,module_id=excluded.module_id,completed=excluded.completed`,[a]);
 await db.query(`insert into course_progress(user_id,module_id,completed) values($1,'m1',false) on conflict(user_id,module_id) do update set user_id=excluded.user_id,module_id=excluded.module_id,completed=excluded.completed`,[a]);
 assert.equal((await db.query('select completed from course_progress')).rows[0].completed,false);
 await db.query(`insert into storage.objects(bucket_id,name) values('assignments',$1)`,[a+'/private.pdf']);
 const assignment=(await db.query('select id from assignments order by sort_order limit 1')).rows[0].id;
 await db.query(`insert into assignment_submissions(user_id,assignment_id,file_name,file_path) values($1,$2,'private.pdf',$3)`,[a,assignment,a+'/private.pdf']);
 await as(b);
 assert.equal((await db.query('select * from admission_letters')).rows.length,0);
 await assert.rejects(db.query(`insert into storage.objects(bucket_id,name) values('assignments',$1)`,[a+'/injected.pdf']));
 await assert.rejects(db.query(`insert into assignment_submissions(user_id,assignment_id,file_name,file_path) values($1,$2,'claimed.pdf',$3)`,[b,assignment,a+'/private.pdf']));
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await assert.rejects(db.query(`insert into storage.objects(bucket_id,name) values('admission-letters',$1)`,[b+'/fake.pdf']));
 await assert.rejects(db.query(`update admission_letters set email_status='sent'`));
 await as(admin);
 await db.query('select admin_set_admission($1,$2)',[appA,'pending']);
 await as(a);
 assert.equal((await db.query('select * from admission_letters')).rows.length,0);
 assert.equal((await db.query(`update course_progress set completed=true returning *`)).rows.length,0);
 assert.equal((await db.query('select completed from course_progress')).rows[0].completed,false);
 }finally{await db.close();}
});
